apiVersion: v1
kind: ConfigMap
metadata: 
  name: env-vars
data:
  AWS_BUCKET: udagram-270184201910-dev
  AWS_PROFILE: default
  AWS_REGION: us-east-1
  JWT_SECRET: supersecretbro
  POSTGRES_DB: udagram-dev
  POSTGRES_HOST: udagram-dev-diego.cueurxgzz9ed.us-east-1.rds.amazonaws.com
  URL: a550f247f65a84832a8f15ab13af8252-1425676260.us-east-1.elb.amazonaws.com:8100